spring.application.name=tourism-app

spring.datasource.url=jdbc:postgresql://localhost:5432/tourismdb
spring.datasource.username=tourism_user
spring.datasource.password=tourism123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# --- Thymeleaf Config ---
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# --- Static Resources (Optional) ---
spring.web.resources.static-locations=classpath:/static/
server.port=8082